-- ตารางของระบบ banpadeng-school-db ที่ระบบรายงานผลการเรียนอ่านร่วมด้วย
-- ใช้เฉพาะสำหรับทดสอบบนเครื่อง (คัดลอกโครงสร้างจากฐานข้อมูลจริง)
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, full_name TEXT NOT NULL, role TEXT CHECK (role IN ('teacher','executive','staff','superadmin') OR role IS NULL), status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled')), created_at TEXT NOT NULL DEFAULT (datetime('now')), approved_at TEXT, approved_by INTEGER REFERENCES users(id), deleted_at TEXT, deleted_by INTEGER REFERENCES users(id), session_version INTEGER NOT NULL DEFAULT 1, password_changed_at TEXT, last_login_at TEXT);
CREATE TABLE auth_login_throttles (throttle_key TEXT PRIMARY KEY, failure_count INTEGER NOT NULL DEFAULT 0, first_failed_at TEXT NOT NULL DEFAULT (datetime('now')), last_failed_at TEXT NOT NULL DEFAULT (datetime('now')), locked_until TEXT);
CREATE TABLE academic_years (id INTEGER PRIMARY KEY AUTOINCREMENT, year_be INTEGER NOT NULL UNIQUE, label TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','closed')), notes TEXT, created_by INTEGER, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE academic_terms (id INTEGER PRIMARY KEY AUTOINCREMENT, academic_year_id INTEGER NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE, term_number INTEGER NOT NULL CHECK (term_number BETWEEN 1 AND 3), name TEXT NOT NULL, start_date TEXT NOT NULL, end_date TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'planned', created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), UNIQUE (academic_year_id, term_number));
CREATE TABLE students (id INTEGER PRIMARY KEY AUTOINCREMENT, student_code TEXT NOT NULL UNIQUE, full_name TEXT NOT NULL, classroom TEXT, grade_level TEXT, photo_url TEXT, health_conditions TEXT, allergies TEXT, status TEXT NOT NULL DEFAULT 'enrolled' CHECK (status IN ('enrolled','transferred','graduated','withdrawn')), created_at TEXT NOT NULL DEFAULT (datetime('now')), national_id TEXT, name_prefix TEXT, first_name TEXT, last_name TEXT, birth_date TEXT);
CREATE TABLE student_details (student_id INTEGER PRIMARY KEY REFERENCES students(id) ON DELETE CASCADE, weight_kg REAL, height_cm REAL, blood_type TEXT, religion TEXT, ethnicity TEXT, nationality TEXT, house_number TEXT, village_no TEXT, road_soi TEXT, subdistrict TEXT, district TEXT, province TEXT, guardian_prefix TEXT, guardian_first_name TEXT, guardian_last_name TEXT, guardian_occupation TEXT, guardian_relationship TEXT, father_prefix TEXT, father_first_name TEXT, father_last_name TEXT, father_occupation TEXT, mother_prefix TEXT, mother_first_name TEXT, mother_last_name TEXT, mother_occupation TEXT, disadvantage TEXT, updated_at TEXT NOT NULL DEFAULT (datetime('now')), gender TEXT);
CREATE TABLE student_enrollments (id INTEGER PRIMARY KEY AUTOINCREMENT, student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE, academic_year_id INTEGER NOT NULL REFERENCES academic_years(id) ON DELETE CASCADE, academic_term_id INTEGER NOT NULL REFERENCES academic_terms(id) ON DELETE CASCADE, grade_level TEXT, classroom TEXT, status TEXT NOT NULL DEFAULT 'enrolled', promoted_from_id INTEGER, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')), UNIQUE (student_id, academic_term_id));
CREATE TABLE learner_class_assignments (id INTEGER PRIMARY KEY AUTOINCREMENT, academic_term_id INTEGER NOT NULL, grade_level TEXT NOT NULL, classroom TEXT NOT NULL, teacher_user_id INTEGER NOT NULL, assigned_by INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT (datetime('now')), UNIQUE (academic_term_id, grade_level, classroom, teacher_user_id));
CREATE TABLE system_settings (setting_key TEXT PRIMARY KEY, setting_value TEXT, updated_by INTEGER, updated_at TEXT NOT NULL DEFAULT (datetime('now')));
